### ISSUE TITLE
Classic Infrastructure Setup

### ISSUE THREAD

**Issue by FaKod** [isaqb-org/curriculum-cloudinfra#2]
The curriculum lacks some classical/conventional cloud setup and pattern, e.g.:
* setup via network zones
* firewalls etc.

**Comment by sw4ma-marhai** [comment]
Needs to be discussed for the next RC

**Comment by anjakammer** [comment]
@FaKod Thanks for your suggestion.

We will come back to you with our suggestions regarding a change.

**Comment by anjakammer** [comment]
@sw4ma-marhai and I came to the conclusion that there is no need to include the "Classic Infrastructure Setup".

However, the fundamentals of network zones and firewalls are concepts, that are also aspects of the cloud, that can be mentioned in Trainings and do not contradict the curriculum. Feel free to include it in your trainings.
