### ISSUE TITLE
Serverless Computing a short introduction

### ISSUE THREAD

**Issue by RobertinoSolanas** [isaqb-org/curriculum-cloudinfra#23]
Since 1,5 years I introduced the topic serverless computing to the audience to clarify what are differences regarding the use cases, architecture and processes to an 'old fashion' microservice architecture. K-native is used as a concrete stack to show how kubernetes can be expanded to some properties like 0 instance behavior and the use of more sophisticated autoscaler algorithms. 

I think it would be worth adding the paradigm serverless computing as a part of the cloudinfra training.

**Comment by anjakammer** [comment]
@RobertinoSolanas Thanks for your suggestion. You are right, the curriculum is missing an explicit learning goal regarding serverless computing.

We will come back to you with a suggestion.

**Comment by anjakammer** [comment]
@RobertinoSolanas I added a proposal #25 to address this issue.
Please note, Co-Curator @sw4ma-marhai did not review this proposal yet, so changes could occur.

**Comment by anjakammer** [comment]
@RobertinoSolanas We will merge PR #25 in 7 days. If you have any additional suggestions on this topic, please make them before then.

**Comment by anjakammer** [comment]
Closed by https://github.com/isaqb-org/curriculum-cloudinfra/pull/25
