### ISSUE TITLE
User Role Management

### ISSUE THREAD

**Issue by FaKod** [isaqb-org/curriculum-cloudinfra#3]
* Control Tower
* Permission Management
* Compliance enforcement (OPA)
* ...

**Comment by sw4ma-marhai** [comment]
Needs to be discussed for the next RC

**Comment by anjakammer** [comment]
@FaKod Thanks for your suggestion.

We will come back to you with our suggestions regarding a change.

**Comment by anjakammer** [comment]
@FaKod #28 adds Permission Management to chapter 6.
Permissions Management is used as a broader term, which can include various specific topics such as User Role Management, RBAC and so on.
Please note, Co-Curator @sw4ma-marhai did not review this proposal yet, so changes could occur.

**Comment by anjakammer** [comment]
@FaKod We will merge PR https://github.com/isaqb-org/curriculum-cloudinfra/pull/28 in 7 days. If you have any additional suggestions on this topic, please make them before then.

**Comment by anjakammer** [comment]
closed by #28
