### ISSUE TITLE
Secret Management

### ISSUE THREAD

**Issue by FaKod** [isaqb-org/curriculum-cloudinfra#4]
- Certificates
- Credentials
- DB Passwords
- secret rotation
- Cloud provider service integration
- ...

**Comment by sw4ma-marhai** [comment]
Needs to be discussed for the next RC

**Comment by RobertinoSolanas** [comment]
Maybe we should add more details on this topic? Secret managers like vault should be mentioned in the training.

**Comment by anjakammer** [comment]
@FaKod @RobertinoSolanas Thanks for your suggestions. 

We will come back to you with a new version that will include Secrets Management options in the cloud.

**Comment by anjakammer** [comment]
@FaKod @RobertinoSolanas #27 contains a proposal for Secrets Management. 
Please note, Co-Curator @sw4ma-marhai did not review this proposal yet, so changes could occur.

**Comment by anjakammer** [comment]
@FaKod @RobertinoSolanas We will merge PR https://github.com/isaqb-org/curriculum-cloudinfra/pull/27 in 7 days. If you have any additional suggestions on this topic, please make them before then.

**Comment by anjakammer** [comment]
Closed by #27
