### ISSUE TITLE
Challenges of Multi Cluster / Hybrid Cloud

### ISSUE THREAD

**Issue by FaKod** [isaqb-org/curriculum-cloudinfra#5]
Specific LG for these kind if challenges

**Comment by sw4ma-marhai** [comment]
Hybrid Cloud is included in learning goals of chapter 1. Multi Cluster needs to be discussed for the next RC

**Comment by RobertinoSolanas** [comment]
This is a really important topic. I see a lot of need to handle cloud workload but more important data to transfer between multiple cloud providers - most of the time between private and public clouds. Encryption, latency and cloud agnostic paradigms are key aspects to overcome these challenges.

**Comment by anjakammer** [comment]
@FaKod @RobertinoSolanas Thanks for your suggestions. We also see, that the challenges of Hybrid/Multi cloud should also be mentioned. As of now, only Hybrid/Multi cloud patterns are mentioned, but not its challenges.

We will come back to you with our suggestions regarding a change.

**Comment by anjakammer** [comment]
@FaKod @RobertinoSolanas #26  is a proposal for Hybrid/Multi Cluster challenges. Additionally, Cloud Migration Patterns are moved to chapter 3.

Please note, Co-Curator @sw4ma-marhai did not review this proposal yet, so changes could occur.

**Comment by anjakammer** [comment]
@FaKod @RobertinoSolanas We will merge PR https://github.com/isaqb-org/curriculum-cloudinfra/pull/26 in 7 days. If you have any additional suggestions on this topic, please make them before then.

**Comment by anjakammer** [comment]
closed by #26
