### ISSUE TITLE
Domains of Cloud Operations

### ISSUE THREAD

**Issue by FaKod** [isaqb-org/curriculum-cloudinfra#6]
- **core** (includes all those cloud operations that are required to set up a cloud environment and that are required to use a cloud provider)
- **network** (constitutes the backbone of cloud operations. It includes all those operations that deal with the networking capabilities of the cloud)
- **security** (starts from the foundation; some people call that job #0 or security by design in which security becomes an intrinsic part of every step. from development top operation)
- **financial** (includes standard principles such as do not overprovision, use only the amount of resources you need, leverage fiscal gains coming from procurement, or evaluate different architectural patterns based on costs)

I like that... Taken from Cloud Operations MEAP

**Comment by sw4ma-marhai** [comment]
Needs to be discussed for the next RC

**Comment by anjakammer** [comment]
@sw4ma-marhai and I came to the conclusion that there is no need to explicitly mention "Domains of Cloud Operations". 
All topics are already covered, with the exception of the financial aspect, which can be mentioned in 

- LG 1-1: Understand and Differentiate Cloud Types
- LG 1-2: Understand Decision Criteria for the Use of Managed Services and Self-Managed Services

However, feel free to include it in your trainings, as it does not contradict the curriculum.
